INSERT INTO lti_permissions_ltipermission (permission, school_id, canvas_role, allow) VALUES
	('manage_people', '*', 'Account Observer', TRUE),
	('manage_people', '*', 'AccountAdmin', TRUE),
	('manage_people', '*', 'Course Head', TRUE),
	('manage_people', '*', 'Course Support Staff', TRUE),
	('manage_people', '*', 'Department Admin', TRUE),
	('manage_people', '*', 'DesignerEnrollment', TRUE),
	('manage_people', '*', 'Faculty', TRUE),
	('manage_people', '*', 'Guest', FALSE),
	('manage_people', '*', 'Harvard-Viewer', FALSE),
	('manage_people', '*', 'Help Desk', TRUE),
	('manage_people', '*', 'Librarian', TRUE),
	('manage_people', '*', 'ObserverEnrollment', FALSE),
	('manage_people', '*', 'SchoolLiaison', TRUE),
	('manage_people', '*', 'Shopper', FALSE),
	('manage_people', '*', 'StudentEnrollment', FALSE),
	('manage_people', '*', 'TaEnrollment', TRUE),
	('manage_people', '*', 'TeacherEnrollment', TRUE),
	('manage_people', '*', 'Teaching Staff', TRUE),
	('manage_people', 'gse', 'Help Desk', FALSE), 
	('manage_people', 'hks', 'Course Head', FALSE),
	('manage_people', 'hks', 'Course Support Staff', FALSE),
	('manage_people', 'hks', 'DesignerEnrollment', FALSE),
	('manage_people', 'hks', 'Librarian', FALSE),
	('manage_people', 'hks', 'TaEnrollment', FALSE),
	('manage_people', 'hks', 'Teaching Staff', FALSE),
	('manage_people', 'hls', 'Account Observer', FALSE),
	('manage_people', 'hls', 'Course Head',  FALSE),
	('manage_people', 'hls', 'Course Support Staff', FALSE),
	('manage_people', 'hls', 'Department Admin', FALSE),
	('manage_people', 'hls', 'DesignerEnrollment', FALSE),
	('manage_people', 'hls', 'Faculty', FALSE),
	('manage_people', 'hls', 'Help Desk', FALSE),
	('manage_people', 'hls', 'Librarian', FALSE),
	('manage_people', 'hls', 'TaEnrollment', FALSE),
	('manage_people', 'hls', 'TeacherEnrollment', FALSE),
	('manage_people', 'hls', 'Teaching Staff', FALSE);
